# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bookshelf_pb2 as bookshelf__pb2


class BookShelfStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getBook = channel.unary_unary(
        '/BookShelf/getBook',
        request_serializer=bookshelf__pb2.BookId.SerializeToString,
        response_deserializer=bookshelf__pb2.Book.FromString,
        )
    self.insertBook = channel.unary_unary(
        '/BookShelf/insertBook',
        request_serializer=bookshelf__pb2.Book.SerializeToString,
        response_deserializer=bookshelf__pb2.Ack.FromString,
        )


class BookShelfServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def insertBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BookShelfServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getBook': grpc.unary_unary_rpc_method_handler(
          servicer.getBook,
          request_deserializer=bookshelf__pb2.BookId.FromString,
          response_serializer=bookshelf__pb2.Book.SerializeToString,
      ),
      'insertBook': grpc.unary_unary_rpc_method_handler(
          servicer.insertBook,
          request_deserializer=bookshelf__pb2.Book.FromString,
          response_serializer=bookshelf__pb2.Ack.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'BookShelf', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
